# Generated by Django 4.2.5 on 2024-10-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Company name"
            ),
        ),
    ]
