# Generated by Django 4.2.5 on 2024-10-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="Employee Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "mobile_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+91777771888",
                        max_length=30,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("password", models.CharField(default="", max_length=255)),
                ("otp", models.CharField(default="", max_length=15)),
                ("fcm_token", models.CharField(max_length=255, null=True)),
                ("session_token", models.CharField(max_length=255, null=True)),
                ("token_version", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="agent_name",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
