# Generated by Django 4.2.5 on 2024-10-03 12:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
