# Generated by Django 4.2.5 on 2024-10-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0002_alter_employee_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[],
        ),
        migrations.AddField(
            model_name="employee",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
