# Generated by Django 4.2.5 on 2024-10-03 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0003_alter_employee_managers_employee_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
